"""empty message

Revision ID: d43011c17877
Revises: 917950d1e40e
Create Date: 2023-07-10 17:07:12.547883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43011c17877'
down_revision = '917950d1e40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('formatting', sa.String(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('formatting')
        batch_op.drop_column('attachments')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
